name: Daily Order Report

on:
  schedule:
    - cron: '30 2 * * *'  # Runs at 08:00 AM IST
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run exportOrders.js
        run: node js/exportOrders.js
        env:
          SHOP: ${{ secrets.SHOP }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
